ADAPT-1802: [hydra-publish] Adapt data classification changes according to our policy
ps-dev/hydra pull request #12
Opened 2023-12-19 08:20 UTC by aman-minz

2023-12-19 09:24 UTC, shreedhar-kc commented on ingestors/kafka/src/main/scala/hydra/kafka/programs/TopicMetadataError.scala
> +      val validValues = s"Valid value is ${if (supportedValues.size == 1) "'" + supportedValues.head + "'" else s"one of [${supportedValues.mkString(", ")}]"}."
Nit: 
I think + can be replaced here with s"'${supportedValues.head}'"

2023-12-21 05:00 UTC, shreedhar-kc requested changes

2023-12-21 05:00 UTC, shreedhar-kc commented on ingestors/kafka/src/main/scala/hydra/kafka/programs/TopicMetadataV2Validator.scala
> +      val correctionRequired = validateSubDataClassificationValues(dataClassification, sdc)
This validation technique is nice.
But I feel like validateSubDataClassificationValues name is a bit misleading. The function is not really validating something but It looks like it is gathering records that needs correction or are incorrect.
Maybe changing the name to "collectInvalidSubDataClassifications()" or "gatherRequiredCorrections() or similar would improve readability.

2023-12-21 07:30 UTC, aman-minz commented on ingestors/kafka/src/main/scala/hydra/kafka/programs/TopicMetadataV2Validator.scala
> +      val correctionRequired = validateSubDataClassificationValues(dataClassification, sdc)
Sure, @shreedhar-kc. I have renamed it to `collectValidSubDataClassificationValues`. Is it fine?

2023-12-21 07:54 UTC, shreedhar-kc submitted a review, later dismissed

2024-01-10 11:00 UTC, abhivermaaa submitted a review, later dismissed
LGTM

2024-01-10 11:18 UTC, aadit-chugh submitted a review, later dismissed

2024-01-10 15:21 UTC, abhivermaaa approved these changes
LGTM

2024-01-10 15:21 UTC, shreedhar-kc approved these changes

2024-01-10 18:08 UTC, merged